; Disable dangerous functions
disable_functions=exec,shell_exec,system,passthru,proc_open,popen,file_get_contents,readfile,fopen,fread,fwrite,file,include,require,include_once,require_once,eval,assert,parse_ini_file,parse_ini_string,fpassthru,getcwd,chdir,chroot,symlink,link,unlink,mkdir,rmdir,dirname

; Restrict file access to /sandbox only
open_basedir=/sandbox

memory_limit=128M
max_execution_time=3
